# Generated by Django 4.0.2 on 2022-02-14 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('image', models.ImageField(blank=True, upload_to='authors_photo', verbose_name='Фото автора')),
                ('summary', models.TextField(max_length=400, verbose_name='Описание')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='CardColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цвет')),
                ('color', models.CharField(max_length=50, verbose_name='HTML тег цвета')),
            ],
            options={
                'verbose_name': 'Цвет карточки',
                'verbose_name_plural': 'Цвета карточек жанров',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
                ('description', models.CharField(max_length=250, verbose_name='Описание жанра')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cardcolor', verbose_name='Цвет карточки')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.CharField(max_length=4, verbose_name='Год издания')),
                ('image', models.ImageField(upload_to='book_image', verbose_name='Обложка')),
                ('summary', models.TextField(max_length=1000, verbose_name='Описание')),
                ('file', models.FileField(upload_to='book_files', verbose_name='Файл книги')),
                ('paper', models.BooleanField(default=True, verbose_name='Печатная версия книги в ЦБС')),
                ('preview', models.BooleanField(default=False, verbose_name='Ознакомительная версия')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorb', to='catalog.author', verbose_name='Автор')),
                ('genre', models.ManyToManyField(related_name='books', to='catalog.Genre', verbose_name='Жанр')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.publisher', verbose_name='Издатель')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
