# Generated by Django 3.0 on 2019-12-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='summary',
            field=models.TextField(default=1, max_length=400, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
