# Generated by Django 3.0 on 2019-12-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Описание жанра'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.ManyToManyField(blank=True, related_name='book_chapter', to='catalog.Chapter', verbose_name='Главы'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Жанр'),
        ),
    ]
