# Generated by Django 3.0 on 2019-12-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191218_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapters',
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание жанра'),
        ),
    ]
