# Generated by Django 4.0.2 on 2022-02-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191220_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='book_files', verbose_name='Файл книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorb', to='catalog.author', verbose_name='Автор'),
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
